// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC17MWiGc07Pfj9cv-3vqYXYogzU4SihnQ',
    appId: '1:263821000282:web:30bc736e7deae15d3ee263',
    messagingSenderId: '263821000282',
    projectId: 'audio-recorder-project',
    authDomain: 'audio-recorder-project.firebaseapp.com',
    storageBucket: 'audio-recorder-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPuv6woDmZCZonMosX_DnV8JvpWdSYBdo',
    appId: '1:263821000282:android:f452b986293103f63ee263',
    messagingSenderId: '263821000282',
    projectId: 'audio-recorder-project',
    storageBucket: 'audio-recorder-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdyLx5Lh1GRnhmKXRt8lrbryqr9FUZdpA',
    appId: '1:263821000282:ios:67d5f1283340c6ab3ee263',
    messagingSenderId: '263821000282',
    projectId: 'audio-recorder-project',
    storageBucket: 'audio-recorder-project.appspot.com',
    iosClientId: '263821000282-vbieeu5puj6u1mp0eoak2hakbr5ifqe6.apps.googleusercontent.com',
    iosBundleId: 'com.example.audioRecorder',
  );
}
